version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 8.0
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore HomeTravelAPI.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build HomeTravelAPI.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -o ./build-output HomeTravelAPI.csproj
      
artifacts:
  files:
    - '**/*'